# Generated by Django 4.1.1 on 2022-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
